networks:
  app_network:
    driver: bridge

volumes:
  minio_data:
  minio_ssh:

services:
  minio:
    image: quay.io/minio/minio:latest
    container_name: minio-ftp
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "9000:9000"
      - "9001:9001"
      - "8021:8021"
      - "8022:8022"
      - "30000-40000:30000-40000"
    networks:
      - app_network
    volumes:
      - minio_data:/data
      - ./ssh:/home/miniouser/.ssh:ro
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:9000/minio/health/ready"]
      interval: 10s
      timeout: 5s
      retries: 10
    command:
      - server
      - /data
      - --ftp=address=:8021
      - --ftp=passive-port-range=30000-40000
      - --sftp=address=:8022
      - --sftp=ssh-private-key=/home/miniouser/.ssh/id_rsa
